
// action by user
export const SUBMIT_RFID_TAG_NUM = 'SUBMIT_RFID_TAG_NUM'
export const CHANGE_RFID_TAG_NUM_TEXT_FIELD = 'CHANGE_RFID_TAG_NUM_TEXT_FIELD'
export const CLEAR_ALL_STATE = 'CLEAR_ALL_STATE'

export const INIT_AUTHENTICATED_RFID_LIST = 'INIT_AUTHENTICATED_RFID_LIST'

export const RFID_TAG_NUM_IS_FOUND = 'RFID_TAG_NUM_IS_FOUND'

export const CHANGE_ERROR_MESSAGE = 'CHANGE_ERROR_MESSAGE'

export const GET_VALID_RFID_TAG_NUM = 'GET_VALID_RFID_TAG_NUM'

export const GET_AUTHENTICATED_ORDER = 'GET_AUTHENTICATED_ORDER'

export const GET_ALL_VALID_ORDER = 'GET_ALL_VALID_ORDER'

export const TOGGLE_DIALOG = 'TOGGLE_DIALOG'