
export const SUBMIT_RFID_CODE = 'SUBMIT_RFID_CODE'
export const CHANGE_RFID_CODE_IN_TEXT_FIELD = 'CHANGE_RFID_CODE_IN_TEXT_FIELD'
export const CLEAR_ALL_STATE = 'CLEAR_ALL_STATE'

export const CHANGE_ERROR_MESSAGE = 'CHANGE_ERROR_MESSAGE'

export const TOGGLE_DIALOG = 'TOGGLE_DIALOG'
